### ISSUE TITLE
fix babel interference with npm run dev

### ISSUE THREAD

**Issue by aaronbanerjee123** [aaronbanerjee123/Discord-Mods#63]
babel interferes and overrides next/js font that we are using so we must figure out how to override this.

**Comment by OM200401** [comment]
Temporary Fix: 
- Used google fonts through link instead of Next font package due to Bable Config Issue
- Imported React to every page that contained React components or hooks due to Bable using an older version of react

**Comment by Devstutya** [comment]
Fixed babel interference by removing babel.config.js and adding jest.config.js. (Switched from babel to next.js compiler)
